# Generated by Django 4.1.5 on 2023-07-02 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_starting_bid_bid_user_bid_listing_current_bid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='User',
            new_name='current_user',
        ),
    ]
